modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="http://https://github.com/Farcr/SavageAndRavage/issues"

[[mods]] #mandatory
modId="savageandravage"
version="${file.jarVersion}"
displayName="Savage & Ravage"
#displayURL="http://example.com/" should this link to the curseforge page?
logoFile="logo.png"
authors="Farcr, Bagel, ComedyArbiter and TallestRed"
credits="MCVinnyQ, for some of the ideas used here, and SmellyModder, for contributing code."
description='''
A mod that improves and expands on illagers through new structures, enemies and challenges.
'''

[[dependencies.savageandravage]] 
    modId="forge"
    mandatory=true
    versionRange="[32.0.88,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.savageandravage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.savageandravage]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[2.1.0,)"
    ordering="AFTER"
    side="BOTH"
