modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/savage-and-ravage/issues"
license = "https://github.com/team-abnormals/savage-and-ravage/blob/main/LICENSE.txt"

[[mods]]
    modId = "savage_and_ravage"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "savage_and_ravage:griefer_helmet"
    configBackground = "savage_and_ravage:textures/block/gloomy_tiles.png"
    authors = "Team Abnormals"
    credits = "Farcr, bageldotjpg, abigailfails, TallestRed, MCVinnyQ"
    displayURL = "https://www.teamabnormals.com/mods/savage-and-ravage"
    displayName = "Savage & Ravage"
    description = '''
    A mod that improves and expands on illagers through new structures, enemies and challenges.
    '''

[[dependencies.savage_and_ravage]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,1.20)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.savage_and_ravage]]
    modId = "forge"
    mandatory = true
    versionRange = "[41.0.100,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.savage_and_ravage]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[6.0.5,)"
    ordering = "AFTER"
    side = "BOTH"