modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://https://github.com/Farcr/SavageAndRavage/issues"

[[mods]] #mandatory
modId="savageandravage"
version="${file.jarVersion}"
displayName="Savage & Ravage"
#displayURL="http://example.com/" should this link to the curseforge page?
logoFile="logo.png"
credits="MCVinnyQ, for many of the ideas."
authors="Farcr, Bagel, TallestEgg and Voliant"
description='''
A mod that improves and expands on illagers through new structures, enemies and challenges.
'''

[[dependencies.savageandravage]] 
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
