modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/savage-and-ravage/issues"
license = "https://github.com/team-abnormals/savage-and-ravage/blob/main/LICENSE.txt"

[[mods]]
    modId = "savageandravage"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    authors = "Team Abnormals"
    credits = "Farcr, bageldotjpg, abigailfails, TallestRed, and MCVinnyQ"
    displayName = "Savage & Ravage"
    description = '''
    A mod that improves and expands on illagers through new structures, enemies and challenges.
    '''

[modproperties.savageandravage]
    catalogueItemIcon = "savageandravage:griefer_helmet"
    configuredBackground = "savageandravage:textures/block/gloomy_tiles.png"

[[dependencies.savageandravage]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.savageandravage]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.savageandravage]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.2.0,)"
    ordering = "AFTER"
    side = "BOTH"